-- DDL

CREATE TABLE FUNCIONARIOS (
    ID INT NOT NULL,
    NOME VARCHAR(50) NOT NULL,
    SALARIO DECIMAL(10,2),
    SETOR VARCHAR2(30),
    PRIMARY KEY (id)
);

CREATE SEQUENCE ID_FUNC START WITH 1 INCREMENT BY 1 NOCACHE;

-- DML
SELECT * FROM funcionarios;

SELECT id, nome, salario, setor AS depto FROM FUNCIONARIOS;


-- DML Insert
INSERT INTO FUNCIONARIOS (ID, NOME, SALARIO) VALUES
(ID_FUNC.NEXTVAL, 'Pedro', 1000);
INSERT INTO FUNCIONARIOS (ID, NOME, SALARIO) VALUES 
(ID_FUNC.NEXTVAL, 'Cleiton', 1000);
INSERT INTO FUNCIONARIOS (ID, NOME, SALARIO) VALUES
(ID_FUNC.NEXTVAL, 'Joao', 1000); 
INSERT INTO FUNCIONARIOS (ID, NOME, SALARIO) VALUES 
(ID_FUNC.NEXTVAL, 'Alexandre', 3000);
INSERT INTO FUNCIONARIOS (ID, NOME, SALARIO) VALUES
(ID_FUNC.NEXTVAL, 'Jose', 2000);

-- DML Update
UPDATE funcionarios SET salario = 1500 WHERE id=1;

-- DML DELETE

DELETE FROM funcionarios WHERE id='1';