-- EXEMPLOS DE UNION ALL

SELECT EMPLOYEE_ID, FIRST_NAME, SALARY FROM EMPLOYEES
UNION ALL
SELECT EMPLOYEE_ID, FIRST_NAME, SALARY FROM E MPLOYEES
ORDER BY 1;

-- EXEMPLOS DE UNION

SELECT EMPLOYEE_ID, FIRST_NAME, SALARY FROM EMPLOYEES
UNION
SELECT EMPLOYEE_ID, FIRST_NAME, SALARY FROM EMPLOYEES
ORDER BY 1;